Added typechecking to pre-commit hook

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -22,6 +22,17 @@ if [ $exit_code -ne 0 ]; then
 fi
 echo "${GREEN}Linting passed${RESET_COLOR} — No errors detected"
 
+# Typechecking
+echo "Running typechecker"
+pnpm run check
+exit_code=$?
+if [ $exit_code -ne 0 ]; then
+  echo "${RED}Typecheck failed${RESET_COLOR} — Errors detected"
+  echo "${exit_message}"
+  exit 1
+fi
+echo "${GREEN}Typecheck passed${RESET_COLOR} — No errors detected"
+
 # Tests
 echo "Running unit tests"
 pnpm run test:single
